Allow players to set their spawns in beds during the daytime
DevotedMC/SimpleAdminHacks pull request #5
Opened 2016-10-17 23:36 UTC by Ameliorate

2016-10-17 23:43 UTC, Maxopoly requested changes

2016-10-17 23:43 UTC, Maxopoly commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java
> +		event.getPlayer().setBedSpawnLocation(event.getClickedBlock().getLocation());
I would recommend increasing the y by 1 here, so players spawn on top of the bed instead of inside

2016-10-17 23:43 UTC, Maxopoly commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java
> +		event.getPlayer().sendTitle("", config.getDaytimeBedSpawnSetMessage());
Using https://github.com/Civcraft/CivModCore/blob/master/src/main/java/vg/civcraft/mc/civmodcore/util/Title.java instead of the deprecated bukkit method is probably better and also allows you more customization

2016-10-17 23:43 UTC, Maxopoly commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/GameTuningConfig.java
> +	private void wireupDaytimeBed(ConfigurationSection config) {
You should do a null check here in case the config doesnt specify a daytimebed section at all

2016-10-18 00:06 UTC, ProgrammerDan requested changes
Besides small changes, looks good.

2016-10-18 00:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/GameTuningConfig.java
> +	private void wireupDaytimeBed(ConfigurationSection config) {
To build on that, set this.daytimeBedEnabled to false if config == null.

2016-10-18 00:34 UTC, Ameliorate commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java
> +		event.getPlayer().setBedSpawnLocation(event.getClickedBlock().getLocation());
setBedSpawnLocation works like vanilla. It spawns the player near the location, not exactly at the location.

2016-10-18 10:28 UTC, Maxopoly commented on src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameTuning.java
> +		event.getPlayer().setBedSpawnLocation(event.getClickedBlock().getLocation());
Oh, in that case I'd recommend adding another listener, which modifies the respawn location to be the actual bed location instead of the vanilla mechanism. We had tons of issues with the vanilla spawning mechanic on civcraft, because it'll lead to death loops often enough.

2016-10-19 05:30 UTC, ProgrammerDan commented
I'm going to go ahead and merge. The comments Max left about respawn location and Title packing should go back on the TODO list as future improvements.

2016-10-19 05:30 UTC, merged